### ISSUE TITLE
No such file or directory: 'files/ca.cert.pem'

### ISSUE THREAD

**Issue by Dunrar** [OzzieIsaacs/calibre-web-test#74]
When trying to run the tests I get the following error:

```
Traceback (most recent call last):
  File "/home/<user>/OpenSource/calibre-web-test/./test/main.py", line 19, in <module>
    generate_ssl_testing_files()
  File "/home/<user>/OpenSource/calibre-web-test/test/helper_certificate.py", line 106, in generate_ssl_testing_files
    _generate_CA()
  File "/home/<user>/OpenSource/calibre-web-test/test/helper_certificate.py", line 56, in _generate_CA
    with open(os.path.join('files', 'ca.cert.pem'),'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'files/ca.cert.pem'
```
System: Manjaro 21.3.5
Python Version: 3.10

**Comment by OzzieIsaacs** [comment]
Could you please check that there is a folder named files in the test folder (this one here: https://github.com/OzzieIsaacs/calibre-web-test/tree/main/test/files)

**Comment by Dunrar** [comment]
Okay, it's there.

**Comment by OzzieIsaacs** [comment]
Then you are calling main from another directory than "tests"? 
I'll update the script to handle this case

Or is the "files" folder not writable to the script?

**Comment by Dunrar** [comment]
No, the first one was it. Thanks!

**Comment by OzzieIsaacs** [comment]
I updated the script to handle this case. There maybe some other problems, as nobody except me is using it (and for my installation everything is configured properly)

**Comment by Dunrar** [comment]
Okay, yes, I have encountered some other problems before getting to this error. Should I open issues for them? Also, I have some PRs open on the Calibre-Web repository. Should I run/write tests for them or do you not require it?

**Comment by OzzieIsaacs** [comment]
Yes please open issues so I can reduce the hurdles for others.
Yes, please write some tests, I‘ currently busy with other projects, I hate writing tests, so the project has currently nearly stalled. Having tests would help me a lot

**Comment by Dunrar** [comment]
Alright!
