### ISSUE TITLE
When running tests, no tests run

### ISSUE THREAD

**Issue by apollo1220** [OzzieIsaacs/calibre-web-test#81]
Hey @OzzieIsaacs,

I'm trying to run these tests so that I can create tests to cover the custom pages feature [here](https://github.com/janeczku/calibre-web/pull/2898#issuecomment-1838945574)

I've gotten to the point where I can run ./test/main.py "successfully". But no tests are actually run. Do you know what I might still need to do in my environment?

* Have pulled calibre-web
* Have pulled calibre-web-test
* Put geckodriver on path
* Created venv and installed from ./test/requirements.txt
* Installed wkhtmltopdf
* Installed calibre
* Have Firefox installed
* Copied config files to ./test and made required modifications

![Screenshot 2023-12-08 095730](https://github.com/OzzieIsaacs/calibre-web-test/assets/8507882/c4aefb35-99ca-4b00-8519-d15bc17e5cdd)

**Comment by OzzieIsaacs** [comment]
The tests are discovered using standard python unittest. Please make sure you start the main script from within the test folder
